env:
  global:
  - CADDY_VERSION=v1.0.2
language: go
go:
  - 1.12.x
go_import_path: github.com/src-d/caddy-build
stages:
  - name: publish

jobs:
  include:
    - name: Publish new build
      stage: publish
      script:
        - go get
        - mkdir $GOPATH/src/github.com/caddyserver || true
        - cd $GOPATH/src/github.com/caddyserver
        - rm -fr caddy || true
        - git clone https://github.com/caddyserver/caddy.git -b $CADDY_VERSION
        - cp $GOPATH/src/github.com/src-d/caddy-build/plugins.go $GOPATH/src/github.com/caddyserver/caddy/caddyhttp/plugins.go
        - cd $GOPATH/src/github.com/caddyserver/caddy/caddy
        - go get github.com/caddyserver/builds
        - go run build.go
        - tar -cvzf caddy.tar.gz caddy
      deploy:
        provider: releases
        api_key:
          secure: 34DV1x+timbzs/AxENc+0EgqCPlkCp1pXdCHi1OMR9x2Ky18Tckc8IrMESLQhGZynO02L4oqfsctzsSyPy4UGsQ2t2RinbE6KuUaDzqdtoVit55d1oQCHTfoa+4EwYjz8JmUUKuGrnjLLZWw+CPiM+NQI86mCWLJ1Mjw1m2jARwSEfBr2SlYXv+OojWDs3a/BHCwW877WD9FE4ABXkhCMnAwO4SYSdNFlpjbbLcBbSfJk777KmYCdQy09nPaDoePduYBqwyrXjZdMpoImPQKAsm0fkc4MIuaXMVX5MhUEH+QaU5d24CxGNwuUtsF0ZQT8h40GxOBoWymP47uIGlCOWNVF/7TbOOHJBlh6nGDC6z+oBNKxLoEtUKjALhJUmRxAX5xahM8wqpSVvviMfVIb4xQL6KLoPdkmyQn12wG/Lg/b0JCSekgI+wvPBNzgs+4GDeiB6XcCLIJ3GUMvBy15sm+fv9p6XqvqVXLMCCsz0KXJdlaM2bpvdktfY1R3PZhhehoZw4qV4l8Go+W14iuOUaEtRutUAlQ+zt+cuLLXPkBjeQ5zDSaBdFaxL6vFgCine0AL5NIZfff6m4Mfm8o/9ac2efBqRU4hXTiy9iSLkXHIHyTV288g2e0u5T14AyvdX+KBKcPH0FXnp62/ecclY1vsoX/7LxperJpbIZCV+0=
        file: $GOPATH/src/github.com/caddyserver/caddy/caddy/caddy.tar.gz
        skip_cleanup: true
        on:
          repo: src-d/caddy-build
          tags: true
